# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 03 Nov 2013 02:43:02 +0000
*               @ALL          1
*               @user         8
