<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: micahredding
 * Date: Sat, 02 Nov 2013 21:47:06 -0500
 */

$conf['title'] = 'Christian Transhumanist Association';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['subscribers'] = 1;

// end auto-generated content
